name: Build

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "bun.lockb"
      - "astro.config.mjs"
      - "tailwind.config.js"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node (Bun)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        shell: "bash"
        working-directory: .
        run: bun install

      - name: Build
        shell: "bash"
        working-directory: .
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"
          name: "build"

  compile-resume:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: List files for debugging
        run: ls -la

      - name: Compile English Resume
        run: typst compile src/templates/resume.typ dist/resume.pdf

      - name: Compile Portuguese Resume
        run: typst compile src/templates/resume-pt.typ dist/resume-pt.pdf

      - name: Upload resume artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"
          name: "resumes"
